import { PageHeader, Change } from '@/components/dashboard';
import { NetChart } from '@/components/charts';
import { PeriodControls } from '@/components/period-controls';
import { TransactionExplorer } from '@/components/transaction-explorer';
import { getDemoData, getOverview } from '@/server/financial-service';
import { parseRange } from '@/server/params';
import { isLiability, money } from '@/domain/finance';
export const metadata = { title: 'Net worth analysis' };
export default async function NetWorth({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const range = parseRange((await searchParams).range); const data = getDemoData(); const s = getOverview(range);
  return <><PageHeader eyebrow="THE BIGGER PICTURE" title="A foundation worth building." description={`Assets, liabilities and the progress between them. Sample balances dated ${data.asOf}.`} range={range} /><div className="metric-grid"><div className="panel metric"><span>Current net worth</span><strong className="positive">{s.current.netWorth === null ? 'Unavailable' : money(s.current.netWorth, true)}</strong><Change change={s.netChange} /></div><div className="panel metric"><span>Total assets</span><strong>{money(s.current.assets, true)}</strong><small>Cash, savings and manually valued property</small></div><div className="panel metric"><span>Total liabilities</span><strong>{money(s.current.liabilities, true)}</strong><small>Outstanding mortgage and credit card debt</small></div></div>{s.current.missingValuation && <p className="notice">Net worth may be incomplete: a mortgage or auto loan has no linked asset valuation.</p>}<section className="panel"><div className="panel-heading"><div><h2>Your net worth over time</h2><p>Recorded balance snapshots · Oldest current observation: {s.current.freshness ?? 'Unavailable'}</p></div><PeriodControls compact value={range} /></div><NetChart history={s.history} expanded /></section><div className="detail-grid contribution-grid">{[false, true].map(liability => <section className="panel" key={String(liability)}><div className="panel-heading"><h2>{liability ? 'Liability breakdown' : 'Asset distribution'}</h2><span className="small muted">Account contribution</span></div>{s.current.balances.filter(b => isLiability(b.account) === liability).map(({ account, snapshot }) => <div className="contribution-row" key={account.id}><div><strong>{account.name}</strong><small>{account.institution} · {snapshot?.date ?? 'No observation'}</small></div><strong>{snapshot ? money(snapshot.balance, true) : 'Missing'}</strong><div className="bar-track"><span style={{ width: `${snapshot ? Math.min(100, Math.abs(snapshot.balance / ((liability ? s.current.liabilities : s.current.assets) || 1)) * 100) : 0}%`, background: liability ? '#ee8a9b' : '#39c5a6' }} /></div></div>)}</section>)}</div><details className="panel snapshot-details"><summary>Inspect historical balances</summary><p className="muted small">Daily synthetic observations. Property valuation is deliberately constant. Values are never inferred from cash flow alone.</p><div className="table-scroll snapshot-table"><table><thead><tr><th>Date</th><th>Assets</th><th>Liabilities</th><th>Net worth</th></tr></thead><tbody>{[...s.history].reverse().map(h => <tr key={h.date}><td>{h.date}</td><td>{money(h.assets, true)}</td><td>{money(h.liabilities, true)}</td><td>{h.netWorth === null ? 'Missing' : money(h.netWorth, true)}</td></tr>)}</tbody></table></div></details><TransactionExplorer records={s.records} accounts={data.accounts} title="Supporting account activity" /></>;
}
