'use client';
import Link from 'next/link';
import { Building2, CreditCard, Home, Wallet } from 'lucide-react';
import type { Dataset } from '@/domain/types';
import { isLiability, money, position } from '@/domain/finance';
import { useDemo } from './demo-context';
import { useState } from 'react';
import { Dialog, DialogContent } from './ui/dialog';
import { TransactionExplorer } from './transaction-explorer';
export function AccountsView({ data }: { data: Dataset }) {
  const { accounts } = useDemo(); const [selected, setSelected] = useState(''); const p = position(data.accounts, data.snapshots, data.asOf);
  const current = p.balances.find(b => b.account.id === selected);
  return <><div className="accounts-summary"><span>{data.accounts.length} reference accounts</span><span>{money(p.assets)} assets</span><span>{money(p.liabilities)} liabilities</span></div><div className="accounts-grid">{p.balances.map(({ account: a, snapshot }) => { const Icon = a.type === 'MANUAL_ASSET' ? Home : a.type === 'CREDIT_CARD' ? CreditCard : isLiability(a) ? Building2 : Wallet; return <button className="panel account-card" key={a.id} onClick={() => setSelected(a.id)}><span className={`icon-tile ${isLiability(a) ? 'violet' : 'emerald'}`}><Icon size={23} /></span><span className="account-type">{a.type.replaceAll('_', ' ')}</span><h2>{a.name}</h2><p>{a.institution}{a.mask && ` · ••${a.mask}`}</p><strong>{money(snapshot?.balance ?? 0, true)}</strong><small>{isLiability(a) ? 'Outstanding balance' : a.type === 'MANUAL_ASSET' ? 'Synthetic manual valuation' : 'Current balance'} · {snapshot?.date}</small></button>; })}</div>{accounts.length > 0 && <section className="panel session-accounts"><h2>Your demo session accounts</h2><p className="muted">Creation previews only. These are excluded from the reconciled reference analytics.</p>{accounts.map(a => <div className="contribution-row" key={a.id}><div><strong>{a.name}</strong><small>{a.type.replaceAll('_', ' ')} · Session only</small></div><strong>{money(a.balance, true)}</strong></div>)}</section>}<p className="methodology-note">All institutions and identifiers are fictional. Debit cards belong to their checking accounts and do not add to net worth.</p><Dialog open={!!current} onOpenChange={open => { if (!open) setSelected(''); }}><DialogContent title={current?.account.name ?? 'Account'} description="Synthetic reference account · No bank connection">{current && <><div className="detail-amount">{money(current.snapshot?.balance ?? 0, true)}</div><dl className="detail-list"><div><dt>Institution</dt><dd>{current.account.institution}</dd></div><div><dt>Account type</dt><dd>{current.account.type.replaceAll('_', ' ')}</dd></div><div><dt>Opening balance</dt><dd>{money(current.account.openingBalance, true)}</dd></div><div><dt>Opening date</dt><dd>{current.account.openingDate}</dd></div><div><dt>Balance observed</dt><dd>{current.snapshot?.date}</dd></div></dl>{current.account.type === 'MANUAL_ASSET' ? <p className="notice">This asset is supported by dated valuation snapshots. It has no transaction ledger. View Net Worth to inspect its contribution.</p> : <Link href={`#account-${current.account.id}`} className="button button-primary" onClick={() => setSelected('')}>See supporting activity below</Link>}</>}</DialogContent></Dialog>{data.accounts.filter(a => a.type !== 'MANUAL_ASSET').map(a => <details className="panel account-activity" key={a.id} id={`account-${a.id}`}><summary>{a.name} · Account transactions</summary><TransactionExplorer records={data.transactions.filter(t => t.accountId === a.id)} accounts={data.accounts} title={a.name} /></details>)}</>;
}
