import { PageHeader, Change } from './dashboard';
import { ExpenseChart, IncomeBars, MonthlyChart, colors } from './charts';
import { TransactionExplorer } from './transaction-explorer';
import { flows, money, sum, type Overview } from '@/domain/finance';
import type { Dataset, Range } from '@/domain/types';
export function AnalysisView({ data, summary, range, kind, category }: { data: Dataset; summary: Overview; range: Range; kind: 'income' | 'expenses'; category?: string }) {
  const income = kind === 'income'; const records = summary.records.filter(t => income ? t.kind === 'INCOME' : ['EXPENSE', 'REFUND'].includes(t.kind));
  const groups = income ? summary.incomeSources : summary.expenseCategories;
  const months = [...new Set(records.map(t => t.date.slice(0, 7)))].sort();
  const monthly = months.map(month => ({ month: new Date(month + '-15T12:00:00Z').toLocaleDateString('en-US', { month: 'short', year: '2-digit', timeZone: 'UTC' }), value: flows(records.filter(t => t.date.startsWith(month)), summary.period.start, summary.period.end)[kind] }));
  const recurring = sum(records.filter(t => t.recurring && t.status === 'POSTED').map(t => t.kind === 'REFUND' ? -t.amount : t.amount));
  const total = summary.totals[kind];
  return <><PageHeader eyebrow={income ? 'UNDERSTAND YOUR EARNINGS' : 'SPEND WITH PERSPECTIVE'} title={income ? 'The sources of your progress.' : 'A closer look at your spending.'} description={`${summary.period.start} through ${summary.period.end} · Posted activity, in USD`} range={range} /><div className="metric-grid"><div className="panel metric"><span>{income ? 'Total income' : 'Net expenses'}</span><strong className={income ? 'blue-text' : 'violet-text'}>{money(total, true)}</strong><Change change={income ? summary.incomeChange : summary.expenseChange} inverse={!income} /></div><div className="panel metric"><span>Recurring {kind}</span><strong>{money(recurring, true)}</strong><small>Explicitly marked recurring activity</small></div><div className="panel metric"><span>{income ? 'Income sources' : 'Spending categories'}</span><strong>{groups.length}</strong><small>{records.filter(t => t.status === 'POSTED').length} posted transactions in this period</small></div></div><div className="detail-grid"><section className="panel"><div className="panel-heading"><div><h2>{income ? 'Income by source' : 'Where it goes'}</h2><p>{income ? 'Your earnings, clearly attributed' : 'Category totals after refunds'}</p></div></div>{income ? <IncomeBars data={groups} /> : <div className="expense-visual"><ExpenseChart data={groups} total={total} /><div className="expense-legend">{groups.map((g, i) => <div key={g.name}><span><i className="legend-dot" style={{ background: colors[i % colors.length] }} />{g.name}</span><strong>{money(g.value)}</strong></div>)}</div></div>}</section><section className="panel"><div className="panel-heading"><div><h2>Monthly {income ? 'income' : 'spending'}</h2><p>Only activity inside the selected window; edge months may be partial</p></div></div>{monthly.length ? <MonthlyChart data={monthly} kind={kind} /> : <div className="empty-state">No activity for this period.</div>}</section></div><p className="methodology-note">{income ? 'Transfers and loan proceeds are excluded. A bank credit alone does not qualify as income.' : 'Card repayments and transfers are excluded. Loan interest counts as expense; principal is separate. Refunds reduce spending.'}</p><TransactionExplorer key={`${range}-${category ?? ''}`} records={records} accounts={data.accounts} initialCategory={category} title={income ? 'Income history' : 'Spending history'} /></>;
}
