import Link from 'next/link';
import { ArrowDownLeft, ArrowUpRight, ChartNoAxesCombined, ChevronRight, CircleDot, Clock3, CreditCard, Lightbulb, ShoppingBag, Wallet } from 'lucide-react';
import type { Dataset, Range, Transaction } from '@/domain/types';
import { money, sum, type Overview } from '@/domain/finance';
import { NetChart, ExpenseChart, IncomeBars, colors } from './charts';
import { PeriodControls } from './period-controls';
import { AddAccount } from './add-account';

export function PageHeader({ eyebrow, title, description, range }: { eyebrow: string; title: string; description: string; range?: Range }) {
  return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div><div className="page-actions">{range && <PeriodControls value={range} />}<AddAccount /></div></div>;
}
export function Change({ change, inverse = false }: { change: Overview['netChange']; inverse?: boolean }) {
  const good = change.movement !== null && (inverse ? change.movement <= 0 : change.movement >= 0);
  return <div className="change-line"><span className={change.movement === null ? 'change neutral' : good ? 'change positive' : 'change negative'}>{change.percentage === null ? 'No comparable baseline' : <>{(change.movement ?? 0) >= 0 ? <ArrowUpRight size={13} /> : <ArrowDownLeft size={13} />}{Math.abs(change.percentage).toFixed(1)}%</>}</span><span>{change.movement === null ? 'More history needed' : `${(change.movement ?? 0) >= 0 ? '+' : '−'}${money(Math.abs(change.movement))} vs. prior period`}</span></div>;
}
function CardHeading({ href, label, icon: Icon, tone }: { href: string; label: string; icon: typeof Wallet; tone: string }) {
  return <div className="card-heading"><div><span className={`icon-tile ${tone}`}><Icon size={19} /></span><h2><Link href={href}>{label}</Link></h2></div><Link className="card-open" href={href} aria-label={`Open ${label} analysis`}><ArrowUpRight size={19} /></Link></div>;
}
export function TransactionIcon({ record }: { record: Transaction }) {
  return <span className={`transaction-icon ${record.direction === 'CREDIT' ? 'credit' : ''}`}>{record.direction === 'CREDIT' ? <ArrowDownLeft size={18} /> : record.kind === 'CARD_PAYMENT' ? <CreditCard size={18} /> : <ShoppingBag size={18} />}</span>;
}
export function Dashboard({ data, summary, range }: { data: Dataset; summary: Overview; range: Range }) {
  const s = summary; const incomeRecurring = sum(s.records.filter(t => t.kind === 'INCOME' && t.status === 'POSTED' && t.recurring).map(t => t.amount));
  const retained = s.totals.income - s.totals.expenses;
  return <><PageHeader eyebrow="YOUR FINANCIAL PICTURE" title="Clarity looks good on you." description="A little perspective on everything you’re building." range={range} /><div className="context-row"><span><span className="status-dot" /> Sample balances as of October 9, 2026</span><span>{data.accounts.length} accounts <span className="context-dot">·</span> {s.period.start} — {s.period.end}</span></div><div className="dashboard-grid">
    <section className="financial-card net-card"><CardHeading href="/net-worth" label="Net worth" icon={ChartNoAxesCombined} tone="emerald" /><div className="card-value">{s.current.netWorth === null ? 'Unavailable' : money(s.current.netWorth)}<span>USD</span></div><Change change={s.netChange} /><PeriodControls value={range} compact /><NetChart history={s.history} /><div className="balance-strip"><div><i className="legend-dot emerald-bg" /><span>Total assets</span><strong>{money(s.current.assets)}</strong></div><div><i className="legend-dot rose-bg" /><span>Total liabilities</span><strong>{money(s.current.liabilities)}</strong></div></div></section>
    <section className="financial-card income-card"><CardHeading href="/income" label="Income" icon={ArrowDownLeft} tone="blue" /><div className="card-value">{money(s.totals.income)}<span>USD</span></div><Change change={s.incomeChange} /><div className="section-kicker">WHERE IT COMES FROM <span>{s.incomeSources.length} sources</span></div><IncomeBars data={s.incomeSources} /><div className="card-footnote"><span><CircleDot size={14} /> {s.totals.income > 0 ? (incomeRecurring / s.totals.income * 100).toFixed(0) : 0}% recurring income</span><Link href={`/income?range=${range}`}>Explore income <ChevronRight size={14} /></Link></div></section>
    <section className="financial-card expense-card"><CardHeading href="/expenses" label="Expenses" icon={ArrowUpRight} tone="violet" /><div className="card-value">{money(s.totals.expenses)}<span>USD</span></div><Change change={s.expenseChange} inverse /><div className="expense-visual"><ExpenseChart data={s.expenseCategories} total={s.totals.expenses} /><div className="expense-legend">{s.expenseCategories.slice(0, 5).map((c, i) => <Link href={`/expenses?category=${encodeURIComponent(c.name)}&range=${range}`} key={c.name}><span><i className="legend-dot" style={{ background: colors[i] }} />{c.name}</span><strong>{money(c.value)}</strong></Link>)}{s.expenseCategories.length > 5 && <Link href={`/expenses?range=${range}`} className="legend-other">+ {s.expenseCategories.length - 5} more categories</Link>}</div></div><div className="card-footnote"><span>Posted expenses, less refunds</span><Link href={`/expenses?range=${range}`}>Explore spending <ChevronRight size={14} /></Link></div></section>
    <section className="financial-card recent-card"><CardHeading href="/transactions" label="Recent transactions" icon={Wallet} tone="amber" /><div className="recent-subtitle">The latest across your accounts <span>DEBITS & CREDITS</span></div><div className="recent-list">{data.transactions.slice(0, 5).map(t => <Link className="recent-row" href={`/transactions?selected=${t.id}`} key={t.id}><TransactionIcon record={t} /><span className="recent-description"><strong>{t.description}</strong><small>{data.accounts.find(a => a.id === t.accountId)?.name} · {t.status === 'PENDING' ? 'Pending' : t.category}</small></span><span className="recent-amount"><strong className={t.direction === 'CREDIT' ? 'positive' : ''}>{t.direction === 'CREDIT' ? '+' : '−'}{money(t.amount, true)}</strong><small>{new Date(t.date + 'T12:00:00Z').toLocaleDateString('en-US', { month: 'short', day: 'numeric', timeZone: 'UTC' })}</small></span></Link>)}</div><Link className="view-transactions" href="/transactions">View all transactions <ChevronRight size={15} /></Link></section>
  </div><div className="insight-strip"><span className="insight-icon"><Lightbulb size={22} /></span><div><div className="insight-label">A LITTLE FINANCIAL PERSPECTIVE <span>Calculated from your sample activity</span></div><p>{retained >= 0 ? <>Your income exceeded spending by <strong>{money(retained)}</strong> this period.</> : <>Spending exceeded income by <strong>{money(Math.abs(retained))}</strong> this period.</>} {s.totals.income > 0 && <>That’s {Math.abs(retained / s.totals.income * 100).toFixed(0)}% of your income.</>}</p><small>Income − net expenses; before transfers, loan principal and asset revaluations.</small></div><Link href={`/income?range=${range}`} className="insight-link">See the breakdown <ChevronRight size={16} /></Link></div><div className="freshness-note"><Clock3 size={12} /> Fixed synthetic reference date · No live bank connections</div></>;
}
