'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { Activity, ArrowDownLeft, ArrowUpRight, ChartNoAxesCombined, ChevronRight, CircleHelp, FlaskConical, LayoutGrid, Menu, Settings2, ShieldCheck, Wallet, X } from 'lucide-react';
import { useState, type ReactNode } from 'react';
import { AddAccount } from './add-account';
import { DemoProvider } from './demo-context';
const links = [
  { href: '/', title: 'Overview', icon: LayoutGrid }, { href: '/accounts', title: 'Accounts', icon: Wallet }, { href: '/transactions', title: 'Transactions', icon: Activity },
  { href: '/net-worth', title: 'Net worth', icon: ChartNoAxesCombined }, { href: '/income', title: 'Income', icon: ArrowDownLeft }, { href: '/expenses', title: 'Expenses', icon: ArrowUpRight },
];
export function Shell({ children }: { children: ReactNode }) {
  const pathname = usePathname(); const [menu, setMenu] = useState(false);
  const title = links.find(l => l.href === pathname)?.title ?? 'Settings';
  return <DemoProvider><div className="app-shell"><aside className={menu ? 'sidebar mobile-open' : 'sidebar'}><Link className="brand" href="/" aria-label="Aureli home"><span className="brand-mark"><ChartNoAxesCombined size={23} strokeWidth={2.4} /></span>aureli<span className="brand-period">.</span></Link><button className="mobile-close icon-button" onClick={() => setMenu(false)} aria-label="Close navigation"><X /></button><div className="workspace-label">PERSONAL WORKSPACE</div><nav aria-label="Main navigation">{links.map((link, i) => <div key={link.href}>{i === 3 && <div className="nav-divider"><span>ANALYTICS</span></div>}<Link onClick={() => setMenu(false)} href={link.href} className={pathname === link.href ? 'nav-link selected' : 'nav-link'} aria-current={pathname === link.href ? 'page' : undefined}><link.icon size={19} />{link.title}{pathname === link.href && <span className="nav-active-dot" />}</Link></div>)}</nav><AddAccount compact /><div className="sidebar-bottom"><div className="demo-panel"><FlaskConical size={18} /><strong>A little room to explore</strong><p>You’re in a synthetic workspace. Your real finances stay private.</p><Link href="/settings" onClick={() => setMenu(false)}>About this demo <ChevronRight size={14} /></Link></div><Link href="/settings" className={pathname === '/settings' ? 'nav-link selected' : 'nav-link'} onClick={() => setMenu(false)}><Settings2 size={18} />Settings</Link><Link href="/settings#methodology" className="nav-link" onClick={() => setMenu(false)}><CircleHelp size={18} />How the numbers work</Link><Link href="/settings" className="profile"><span className="avatar">JD</span><span><strong>Jordan Davis</strong><small>Personal workspace · Demo</small></span><ChevronRight size={16} /></Link></div></aside>{menu && <button className="mobile-scrim" onClick={() => setMenu(false)} aria-label="Close navigation overlay" />}<div className="main-shell"><header className="topbar"><div className="breadcrumb"><button className="mobile-menu icon-button" onClick={() => setMenu(true)} aria-label="Open navigation"><Menu size={21} /></button><span>Workspace</span><ChevronRight size={14} /><strong>{title}</strong></div><div className="topbar-right"><span className="private-label"><ShieldCheck size={14} /> Private by design</span><Link href="/settings" className="demo-badge"><span /> Demo mode</Link><Link href="/settings" className="avatar small-avatar" aria-label="Profile and settings">JD</Link></div></header><main id="main-content">{children}</main><footer className="footer"><span><ShieldCheck size={13} /> Synthetic data. Real perspective.</span><span>USD · America/New_York</span></footer></div></div></DemoProvider>;
}
