import { describe, expect, it } from 'vitest';
import { defaultMapping, parseCSV } from '../../src/imports/csv';
const header = 'date,description,amount,direction,kind,currency,category\n';
describe('CSV normalization and idempotency', () => {
  it('normalizes a debit amount with explicit expense classification', () => { const rows = parseCSV(header + '2026-10-01,Market,83.42,DEBIT,EXPENSE,USD,Groceries', 'a', 'w'); expect(rows[0].transaction?.amount).toBe(8342); expect(rows[0].transaction?.source).toBe('CSV'); expect(rows[0].transaction?.kind).toBe('EXPENSE'); });
  it('reports bad dates, currencies and classification per row', () => { const rows = parseCSV(header + '2026-02-30,Market,1,DEBIT,EXPENSE,USD,Groceries\n2026-10-01,Market,1,DEBIT,EXPENSE,EUR,Groceries\n2026-10-01,Market,1,DEBIT,UNKNOWN,USD,Groceries', 'a', 'w'); expect(rows.every(r => r.error !== null)).toBe(true); expect(rows.map(r => r.row)).toEqual([2, 3, 4]); });
  it('detects duplicates in one file and across re-imports', () => { const row = '2026-10-01,Market,83.42,DEBIT,EXPENSE,USD,Groceries'; const rows = parseCSV(header + row + '\n' + row, 'a', 'w'); expect(rows.map(r => r.duplicate)).toEqual([false, true]); const again = parseCSV(header + row, 'a', 'w', defaultMapping, new Set([rows[0].transaction!.fingerprint!])); expect(again[0].duplicate).toBe(true); });
  it('keeps deduplication scoped to the account', () => { const row = header + '2026-10-01,Market,83.42,DEBIT,EXPENSE,USD,Groceries'; expect(parseCSV(row, 'a', 'w')[0].transaction?.fingerprint).not.toBe(parseCSV(row, 'b', 'w')[0].transaction?.fingerprint); });
  it('supports debit/credit columns without inferring economic classification', () => { const text = 'Date,Memo,Debit,Credit,Type\n2026-10-01,Move,500,,TRANSFER\n2026-10-02,Payment,,500,CARD_PAYMENT'; const rows = parseCSV(text, 'a', 'w', { date: 'Date', description: 'Memo', debit: 'Debit', credit: 'Credit', kind: 'Type' }); expect(rows.map(r => r.transaction?.direction)).toEqual(['DEBIT', 'CREDIT']); expect(rows.map(r => r.transaction?.kind)).toEqual(['TRANSFER', 'CARD_PAYMENT']); });
  it('rejects ambiguous debit/credit and inconsistent sign', () => { expect(parseCSV('date,description,debit,credit,kind\n2026-10-01,Move,3,2,TRANSFER', 'a', 'w', { date: 'date', description: 'description', debit: 'debit', credit: 'credit', kind: 'kind' })[0].error).not.toBeNull(); expect(parseCSV(header + '2026-10-01,Pay,-3,CREDIT,INCOME,USD,Salary', 'a', 'w')[0].error).not.toBeNull(); });
  it('rejects oversized or malformed input and missing columns', () => { expect(() => parseCSV('a'.repeat(2097153), 'a', 'w')).toThrow('2 MB'); expect(() => parseCSV('date,description\n2026-10-01,Test', 'a', 'w')).toThrow('Missing mapped'); expect(() => parseCSV(header + '2026-10-01,too,few', 'a', 'w')).toThrow('Malformed'); });
});
